# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  # Show all issues from all linters
  exclude-use-default: false
  # Exclude all issues from examples directory
  exclude-rules:
    - path: examples
      linters:
        - typecheck
    # False positive: "may" appears twice because it's both the full month name and abbreviation
    - path: parser_ordinal.go
      linters:
        - gocritic
      text: "badRegexp.*may.*is duplicated"
    # False positive: "decembre" is correct French spelling, not a typo of English "december"
    - linters:
        - misspell
      text: "decembre.*misspelling.*december"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - revive

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - errorsas
      - httpresponse
      - nilfunc
      - printf
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unusedresult
  staticcheck:
    checks: ["all"]
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - unnamedResult

